dataset:
 classname: "Ogbn"
 name: "arxiv"
 root: "/home/ssq/test_data/"
model:
 gnn_type: 'gcn'
 hidden_dim: 256
 dropout: 0.5
 n_layers: 3
 step_size: 0.001
 augM: 3
 batch_norm: True
task:
 lr: 0.01
 seed: 12345
 epochs: 500
 patience: 80
 weight_decay: 0
# dataset:
#  classname: "Ogbn"
#  name: "arxiv"
#  root: "/home/ssq/test_data/"
# model:
#  gnn_type: 'sage'
#  hidden_dim: 256
#  dropout: 0.5
#  n_layers: 3
#  step_size: 0.001
#  augM: 3
#  batch_norm: True
# task:
#  lr: 0.01
#  seed: 12345
#  epochs: 500
#  patience: 80
#  weight_decay: 0
# dataset:
#  classname: "Ogbn"
#  name: "arxiv"
#  root: "/home/ssq/test_data/"
# model:
#  gnn_type: 'gat'
#  hidden_dim: 256
#  n_heads: '8,8,1'
#  dropout: 0.6
#  attn_dropout: 0.6
#  n_layers: 3
#  step_size: 0.001
#  augM: 3
#  amp: 2
#  batch_norm: True
# task:
#  lr: 0.002
#  seed: 12345
#  epochs: 500
#  patience: 100
#  weight_decay: 0