dataset:
  classname: "Ogbn"
  name: "arxiv"
  root: "/home/ssq/test_data/"
sampler:
  training:
    name: "NeighborSampler"
    layer_sizes: "15, 10, 5"
    prob_type: "normalize"
    replace: False 
  eval:
    name: "NeighborSampler"
    layer_sizes: "-1"
    replace: False
model:
  gnn_type: 'sage'
  hidden_dim: 256
  dropout: 0.5
  alpha: 4
  beta: 4
  n_layers: 3
  feat_norm: "none"
  batch_norm: True
task:
  name: "NodeClassification_Sampling"
  lr: 0.003
  seed: 12345
  epochs: 300
  patience: 30
  weight_decay: 0
  train_batch_size: 1024
  eval_batch_size: 4096 
  train_num_workers: 12 
  eval_num_workers: 12
  eval_together: True 
  eval_freq: 2