dataset:
  classname: "Planetoid"
  name: "cora"
  root: "/home/ssq/test_data/"
  split: "official"
sampler:
  name: "FastGCNSampler"
  inductive: False
  adj_process: "LaplacianGraphOp"
  layer_sizes: "256-256"
  prob_type: "normalize"
  replace: True
model:
  name: "FastGCN"
  hidden_dim: 128
  dropout: 0.5
  num_layers: 2
task:
  train_batch_size: 256
  eval_batch_size: 256
  epochs: 30
  lr: 0.1
  weight_decay: 0.00005
  loss_fn: "nll_loss"

