dataset:
  classname: "Planetoid"
  name: "cora"
  root: "/home/ssq/test_data/"
sampler:
  train:
    pre_sampling_graphs: 10
    samplertype: "Node"
    nodebudget: 2048
    pre_sampling_op: "RwGraphOp"
model:
  hidden_dim: 128
  dropout: 0.5
  num_layers: 2
task:
  train_batch_size: 2048
  epochs: 100
  lr: 0.01
  weight_decay: 0.00005
  seed: 42

