dataset:
  classname: "Planetoid"  
  name: "pubmed"
  root: "/home/ssq/test_data/"
  split: "full"
sampler:
  training:
    name: "NeighborSampler"
    inductive: False
    layer_sizes: "10,5"
    prob_type: "normalize"
    replace: False
    post_sampling_op: "RwGraphOp"
    sparse_type: "torch"
  # eval:
  #   name: "NeighborSampler"
  #   inductive: False
  #   layer_sizes: "-1"
  #   prob_type: "normalize"
  #   post_sampling_op: "RwGraphOp"
  #   sparse_type: "torch"
model:
  name: "GraphSAGE"
  hidden_dim: 256
  dropout: 0.5
  num_layers: 2
task:
  name: "NodeClassification_Sampling"
  train_batch_size: 1024
  train_num_workers: 0
  # eval_batch_size: 1024
  # eval_num_workers: 5
  # eval_together: True
  epochs: 20
  lr: 0.03
  weight_decay: 0.00005
  loss_fn: "nll_loss"

