dataset:
  classname: "Planetoid"  
  name: "pubmed"
  root: "/home/ssq/test_data/"
  split: "full"
sampler:
  training:
    name: "NeighborSampler"
    inductive: False
    layer_sizes: "5,5"
    prob_type: "normalize"
    replace: True
    post_sampling_op: "LaplacianGraphOp"
model:
  name: "LazyGCN"
  hidden_dim: 128
  dropout: 0.5
  num_layers: 2
  max_workers: 5
  train_batch_size: 2048
task:
  name: "NodeClassification_RecycleSampling"
  epochs: 20
  lr: 0.1
  weight_decay: 0.00005
  loss_fn: "nll_loss"

